### ISSUE TITLE
Bug: Unhandled Promise rejection when bidding on proposer slot

### ISSUE THREAD

**Issue by jacque006** [thehubbleproject/hubble-contracts#612]
```
block 1344      Slot progress   9/10
block 1345      Slot progress   0/10
New slot 128
Auctioning slot coordinator 0x0000000000000000000000000000000000000000 0.0 ETH
Bid 0.000000000000000001 ETH
(node:15276) UnhandledPromiseRejectionWarning: Error: invalid BigNumber value (argument="value", value=null, code=INVALID_ARGUMENT, version=bignumber/5.3.0)
    at Logger.makeError (/root/hubble/hubble-contracts/node_modules/@ethersproject/logger/src.ts/index.ts:213:28)
    at Logger.throwError (/root/hubble/hubble-contracts/node_modules/@ethersproject/logger/src.ts/index.ts:225:20)
    at Logger.throwArgumentError (/root/hubble/hubble-contracts/node_modules/@ethersproject/logger/src.ts/index.ts:229:21)
    at Function.BigNumber.from (/root/hubble/hubble-contracts/node_modules/@ethersproject/bignumber/src.ts/bignumber.ts:291:23)
    at Formatter.bigNumber (/root/hubble/hubble-contracts/node_modules/@ethersproject/providers/src.ts/formatter.ts:183:26)
    at Function.Formatter.check (/root/hubble/hubble-contracts/node_modules/@ethersproject/providers/src.ts/formatter.ts:428:42)
    at Formatter.transactionResponse (/root/hubble/hubble-contracts/node_modules/@ethersproject/providers/src.ts/formatter.ts:324:55)
    at JsonRpcProvider.<anonymous> (/root/hubble/hubble-contracts/node_modules/@ethersproject/providers/src.ts/base-provider.ts:1412:39)
    at step (/root/hubble/hubble-contracts/node_modules/@ethersproject/providers/lib/base-provider.js:48:23)
    at Object.next (/root/hubble/hubble-contracts/node_modules/@ethersproject/providers/lib/base-provider.js:29:53)
(node:15276) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 19)
block 1346      Slot progress   1/10
```

**Comment by jacque006** [comment]
This is most likely due to geth adding EIP-1559 support in v1.10.4 and ethers.js not yet supporting it. Will wait on the release of https://github.com/ethers-io/ethers.js/issues/1610 and re-test with new version.
